name: Build & Push Frontend

on:
    push:
        branches: ['main']
        paths: ['deploy/docker-compose.yaml', 'app/**']
    workflow_dispatch:
        inputs:
            reason:
                description: 'why'
                required: false
                default: 'just for fun'

env:
    FRONTEND_IMAGE: ghcr.io/dikobrazik/squad-speak-frontend

jobs:
    build-frontend:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: 'Create env file'
              run: |
                  echo "${{ secrets.ENV_FRONTEND }}" > ./app/.env

            - name: Login to Dockerhub
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Frontend
              uses: docker/build-push-action@v5
              with:
                  context: ./app
                  file: ./app/deploy/Dockerfile
                  push: true
                  tags: ${{ env.FRONTEND_IMAGE }}
