name: Deploy All Services

on:
  push:
    branches: ['main']
    paths: ['.github/workflows/deploy.yaml', 'deploy/docker-compose.yaml', 'deploy/scripts/**']
  workflow_dispatch:
  workflow_run:
    workflows:
      - Build & Push Frontend
      - Build & Push Backend
      - Build & Push Nginx
    types:
      - completed

concurrency:
  group: deploy-all
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy deploy files to remote server using SSH
        uses: appleboy/scp-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            strip_components: 1
            source: 'deploy/docker-compose.yaml'
            target: '/home/actions/squad-speak'

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ github.actor }}
          ENV_DOCKER: ${{ secrets.ENV_DOCKER }}
          ENV_FRONTEND: ${{ secrets.ENV_FRONTEND }}
          ENV_BACKEND: ${{ secrets.ENV_BACKEND }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: GITHUB_TOKEN,GITHUB_USER,ENV_DOCKER,ENV_FRONTEND,ENV_BACKEND
          script_path: ./deploy/scripts/deploy.sh


